name: Citrus
favicon: null
layout_spectrum: 0.3017768517602235
typography_spectrum: 0.12830825243145227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5745038315653801
  lightness: 0.18411651160568
  saturation: 0.3791281944140792
  rhythmicContrast: 0.6920511953067034
purpose: []
